### ISSUE TITLE
iex_debugTrap link error

### ISSUE THREAD

**Issue by 0xRED** [openexr/openexr#188]
when using adsk fbx lib & other lib that include your lib we get link error over debugTrap, any plan to fix that ?

**Comment by meshula** [comment]
You can get around the problem by defining your own iex_debugTrap() as

void iex_debugTrap() { std::cout << "what the heck" << std::endl; }

I suggest reporting this problem to Autodesk as the issue lies with the fbx distribution.

**Comment by cary-ilm** [comment]
Looking into the OpenEXR issue backlog.  Does not seem to be an OpenEXR issue, so closing.

**Comment by geniusisme** [comment]
Why the issue is not considered to be an OpenEXR issue?
iex_debugTrap is a part of Iex, which is a part of OpenEXR.
Issue is occurring when linking separate versions of libraries together, which is explicitly supported with namespace-mangling mechanism.
But iex_debugTrap is not namespaced, and that breaks promise, given by the library.

**Comment by meshula** [comment]
That is a good point about the namespacing introduced across the rest of the library to resolve these kinds of collisions. TBH iex_debugTrap should probably be removed. It's not a normal sort of thing to find in a modern library. I personally added this mechanism a loooooong time ago, when debuggers such as the Visual Studio debugger were unable to break when exceptions were thrown. Those days are long gone, and the mechanism is archaic.
