### ISSUE TITLE
RLE Broken for 32-bit formats

### ISSUE THREAD

**Issue by acjones** [openexr/openexr#194]
We noticed that when compressing 32-bit files with RLE in Nuke, for many values other than 0.0, a constant color image will end up the same size as an uncompressed .exr.  From looking at the code, this seem to be because the bytes are being separated into two streams of bytes, each with 16 bits, but then the pattern recognition for RLE only looks at one byte at a time.

A black image with all values at 0.0 (0x0) compresses perfectly, because all bytes are 0.  A constant image at 1.0 (0x3f800000) results in a file that's exactly half the size of the uncompressed image, because the second stream of bytes is all 0, but the first is alternating between 3f and 80.  A value of 1.1 (0x3f8ccccd) has no effective compression and is the same size as uncompressed.

It seems that the best compression would likely be achieved by building 4 byte streams and compressing them individually for a 32-bit value, for the same reason that compressing 2 byte streams makes sense for a 16-bit value.  Otherwise, it could be compressed as two 16-bit streams instead of 2 8-bit streams.

Presumably, this could be fixed with some pretty simple edits to how bytes are reordered in RleCompressor::compress in ImfRleCompressor.cpp, but I understand the harder work would be in dealing with backward compatibility for legacy RLE-compressed 32-bit files.

**Comment by johannesvollmer** [comment]
Absolutely! The same algorithm is also used for other compression types, such as ZIP and ZIPS, which would probably also improve by using 4 streams. By simply always dividing into 4 byte streams, even for 'half float' images, one could have achieved good compression every time, but now it's too late. I assume that, if at all, this could be incorporated into `OpenEXR 3`...

**Comment by acjones** [comment]
It's in some ways beyond the scope of the issue, but I think an interesting way to handle it might be to introduce a notion of compatibility profiles.  As an example, when DWA was added, the casual application user's experience of exporting exrs between apps wasn't great, as the readers don't necessarily tell you what compression types are supported, and the average user doesn't always know which features came with what versions of the library, and even which version of OpenEXR is in use with a given app.  With profiles, a user could tell the writing library to target an earlier profile to make exrs that are backwards-compatible with an earlier OpenEXR version.  And by introducing newer profiles, the library could make tweaks to existing implementations without causing unexpected behaviors in the older releases.

**Comment by johannesvollmer** [comment]
It is possible to target lower versions when writing a file, concerning the file format specification, but I don't know if the official library provides an API for that. Each file has some bits which tells the file reader what to expect, so that it can quit early when recognizing an unsupported feature. However, as far as I know, these bits don't include the compression method.

**Comment by peterhillman** [comment]
I'd say it's not so much about 'targeting lower versions' as the opposite: new features in EXR are "opt-in"  - unless you specifically switch to the new compression types, or write channels into more than one part, you will be compatible with lower versions. Tools shouldn't switch to those if they have been asked to target a lower version. Out of caution, the default settings should be the most backwards compatible.

It would be good to have clearer descriptions of what features won't work in which older versions if there's another change. I think there have only been two file format changes in the last 10 years (DWA compression in 2.1, deep and multipart in 2.0) so an API to manage that might be overkill.

Andy, concerning the original point: The "broken" in the issue title means it usually produces files which have no compression but doesn't actually break anything? Are there situations in which a 32-bit float file cannot be read if it's written with RLE compression? 

I wouldn't expect RLE compression of 32 bit floats to perform well, because I would expect a close-to-zero chance of having a run of non-zero floats in an image channel. It's possible that you get a run of 1.0 values, but likely that would be a mask/alpha channel, which probably should be written as a half.

As stated above, many lossless compression schemes in EXR assume 16 bit data and perform poorly on 32 bit data. I agree it would be nice to have a new lossless compression type that's more aware of the underlying type of each channel. That would require being "honest" about the nature of the data written - if you are writing a 32 bit float which isn't luminance data (e.g. hashing a string to encode an object ID!) you'd have to use UINT rather than FLOAT type. Then the compressor would expect randomly distributed values that may repeat exactly within the same scanline/tile, rather than neighbouring values being close but not identical, as you'd get in a typical image channel.

**Comment by KevinJW** [comment]
On Wed, Oct 3, 2018 at 3:45 AM, peterhillman <notifications@github.com>
wrote:

> It would be good to have clearer descriptions of what features won't work
> in which older versions if there's another change. I think there have only
> been two file format changes in the last 10 years (DWA compression in 2.1,
> deep and multipart in 2.0) so an API to manage that might be overkill.
>

For completeness I recall an issue relating to channel/attribute name
lengths being increased in v1.7.0, though I don't think that adds much
to/from the argument, we worked around it at the time by creating a Nuke
node to explicitly truncate the lengths.

Kevin

**Comment by peterhillman** [comment]
I'm closing this since it appears that RLE compression doesn't actually break with 32-bit formats. The files do read and write correctly, but are much larger than expected. As @johannesvollmer points out most lossless compression schemes in OpenEXR assume all data is half float so suffer from this problem to some extent. New compression schemes may be added at a later date that may pay more attention to the data type to address this sort of problem
