### ISSUE TITLE
OpenEXR write resorts channels on its own

### ISSUE THREAD

**Issue by irieger** [openexr/openexr#203]
I reported a bug that I first thought is a problem in OpenImageIO earlier today so I'll just leave a link and a short description here. For further elaboration see the issue postet here: https://github.com/OpenImageIO/oiio/issues/1480

Here is the short: For two weeks I was searching a bug in a software I'm writing as my image viewer was showing different results than expected while I couldn't find any bug regarding this issue in my  code.

Just today I discovered that OpenEXR resorts the channels internally so when I just load the image the channels are in an alternate order and only numbered naming with leading Zeros could save me. I'd consider this a bug. What do you think? (At least when unnamed the channels should stay in order I'd say...)

**Comment by ehanway-ilm** [comment]
Sorry for the time you lost chasing this down.  OpenEXR doesn't actually support unnamed channels, and it's been using a sorted-by-name container for the channel list since its beginning.  It looks like if we were to change it now, it would break the part of the API that handles groups of channels as layers (ChannelList::channelsInLayer()), since that assumes that the subset of channels corresponding to a layer will be sorted so that they're contiguous in the channel list.

In contrast, the parts of a multi-part file will be stored in the order passed in.  Would a multi part file be a fit for your use case?

**Comment by irieger** [comment]
I already solved the problem by naming the channels. I don't know how well this topic is documented in the OpenEXR documentation which I ready in most parts some time ago. In the OIIO documentation it wasn't that clear but I already reported it there. I understand that the solving this problem would be an unexpected API change but still I don't really like this behaviour of OpenEXR.

As I don't have the time to dive further into this I can't search for the part myself but is the channel naming with unnamed 1, 2 ... happening in OIIO or in OpenEXR. It would at least make sense to think about doing default names with leading zeros to prevent unexpected sorting.
