### ISSUE TITLE
Can RgbaOutputFile use 32-bit float?

### ISSUE THREAD

**Issue by mfeemster** [openexr/openexr#237]
I have the source building and running and am following the examples to learn how to write an EXR image. I notice that RgbaOutputFile hard codes the format of each RGBA channel to type HALF.

I was wondering if there is a way to set it to FLOAT to use full 32-bit precision for each channel?

Thanks.

**Comment by peterhillman** [comment]
Apologies for the very late response. In short: there isn't a way.

The RgbaOutputFile class only accepts half-float pixel data, which is why it uses HALF storage within th file. For RgbaOutputFile to support float data, there would also have to be a 'float' version of the Rgba type to provide the pixel data.

For anything other than writing half-float RGBA in a single part, the General Interface for Scanline Based Files should be used, via the OutputFile or MultiPartOutputFile classes. See the [Reading and Writing OpenEXR image Files document](https://www.openexr.com/documentation/ReadingAndWritingImageFiles.pdf) for details. These interfaces are more versatile. For example, you can omit the A alpha channel completely, write it as half float and RGB as 32 bit float, or separate it into a separate part so it can be skipped when it isn't required.

Providing float support in RgbaOutputFile (and presumably RgbaInputFile as well) seems like it would duplicate a lot of effort for a small use-case without providing any extra functionality.
